sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t R4Di/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true R4Di/docker-react npm run test -- --coverage